HTTP/1.1 201 Created
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 138
ETag: W/"8a-qanZn2x/PXLv35Y8EwO7T69XJck"
Date: Mon, 19 Jul 2021 16:13:23 GMT
Connection: close

{"title":"ejemplo con token","url":"unn url","author":"xsrpm","likes":0,"user":"60f325e148d54727043308d0","id":"60f5a4a2a6009638b8a8d448"}